=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/practise.dtd
<!ELEMENT Result (Name,Gender,Address,Email,Subject,Marks+,College)>
<!ELEMENT Name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT College (#PCDATA)>
<!ATTLIST College u_d CDATA #REQUIRED>
<!ATTLIST College u_d IDREF #REQUIRED>
<!ATTLIST Name enrolled CDATA #REQUIRED>
<!ATTLIST Name enrolled ID #REQUIRED>
<!ELEMENT Address (#PCDATA)>
<!ATTLIST Address area CDATA #REQUIRED>
<!ELEMENT Gender ( Male | Female )>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT Email (#PCDATA)>
<!ATTLIST Email above NMTOKEN #REQUIRED>
<!ELEMENT Subject (#PCDATA)>
<!ELEMENT Marks (#PCDATA)>

=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/practise.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE Result SYSTEM "practise.dtd">
<Result>
	<Name enrolled="185">
		<fname>Sujal</fname>
		<lname>Prajapati</lname>
	</Name>
	<Gender>
		<Male>yes</Male>
	</Gender>
	<Address area="Bapunagar">Ahmedabad</Address>
	<Email above=":">sujal123@gmail.com</Email>
	<Subject>XML</Subject>
	<Marks>90</Marks>
	<College u_d="A01"> GLS </College>
</Result>
