=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac_7.dtd
<!-- Create an XML document Email where it contains the following data :
 Email (from , to ,content ( person , exercises(exercise (topic ,
description) ) , course ).
Create An External DTD for the above XML document where 
• Content element of email should be mixed content.
• Exercises can have multiple exercise element. -->
<!ELEMENT Email (#PCDATA | from | to | content)*>
<!ELEMENT content (person,exercises,course)>
<!ELEMENT exercises (exercise+)>
<!ELEMENT exercise (topic,description)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT person (#PCDATA)>
<!ELEMENT topic (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT course (#PCDATA)>

=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac7.xml
<?xml version="1.0"?>
<!--Create an XML document Email where it contains the following data :
 Email (from , to ,content ( person , exercises(exercise (topic ,
description) ) , course ).
Create An External DTD for the above XML document where 
• Content element of email should be mixed content.
• Exercises can have multiple exercise element.-->
<!DOCTYPE Email SYSTEM "prac_7.dtd">
<Email>send to fast
	<from>sujal</from>
	<to>kirtan</to>
	<content>
		<person>purav</person>
		<exercises>
			<exercise>
				<topic>study</topic>
				<description>padh le padh le</description>
			</exercise>
			<exercise>
				<topic>game</topic>
				<description>head short</description>
			</exercise>
		</exercises>
		<course>IMSCIT</course>
	</content>recieve
</Email>
