=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac_1.dtd
<!--Create an XML document for storing personal information about
student where it contains the following data:
Personal Info( Roll no, Name, Address, Mobile, DOB, Age,Qualification)
Create An External DTD for the above XML document.-->
<!ELEMENT Personal_info (Roll_no, Name, Address, Mobile, DOB, Age,Qualification)>
<!ELEMENT Roll_no (#PCDATA)>
<!ELEMENT Name (#PCDATA)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Mobile (#PCDATA)>
<!ELEMENT DOB (#PCDATA)>
<!ELEMENT Age (#PCDATA)>
<!ELEMENT Qualification (#PCDATA)>

=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac1.xml
<?xml version="1.0"?>
<!--Create an XML document for storing personal information about
student where it contains the following data:
Personal Info( Roll no, Name, Address, Mobile, DOB, Age,Qualification)
Create An External DTD for the above XML document.-->
<!DOCTYPE Personal_info SYSTEM "prac_1.dtd">
<Personal_info>
	<Roll_no>81</Roll_no>
	<Name>Sujal</Name>
	<Address>Ahmedabad</Address>
	<Mobile>8596745256</Mobile>
	<DOB>5/6/2024</DOB>
	<Age>19</Age>
	<Qualification>12th pass</Qualification>
</Personal_info>
