=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac_9.dtd
<!--Create an XML document Letter where it contains the following data :
Letter (contact (name , address , city ,pin ,state , flag) , salutation
, paragraph , closing , signature ) . The “contact “ element has an
attribute “type” where it will declare type of person (eg :
manager , officer etc as a value) .
Create An External DTD for the above XML document where 
• contact should come atleast once.
• flag element should an empty element
• “flag” element has an attribute “gender” where it will declare as
a male or female as a value and male as a default value.
• The attribute type has a fixed value “sender”-->
<!ELEMENT Letter (contact+,salutation,paragraph,closing,signature)>
<!ELEMENT contact (name,address,city,pin,state,flag)>
<!ATTLIST contact type CDATA #FIXED "sender">
<!ELEMENT salutation (#PCDATA)>
<!ELEMENT paragraph (#PCDATA)>
<!ELEMENT closing (#PCDATA)>
<!ELEMENT signature (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT address (#PCDATA)>
<!ELEMENT city (#PCDATA)>
<!ELEMENT pin (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT flag EMPTY>
<!ATTLIST flag gender (male | female) #REQUIRED>

=== Sujal-prajapati07/College_programs/XML/Moodle_Assignment2/prac9.xml
<?xml version="1.0"?>
<!--Create an XML document Letter where it contains the following data :
Letter (contact (name , address , city ,pin ,state , flag) , salutation
, paragraph , closing , signature ) . The “contact “ element has an
attribute “type” where it will declare type of person (eg :
manager , officer etc as a value) .
Create An External DTD for the above XML document where 
• contact should come atleast once.
• flag element should an empty element
• “flag” element has an attribute “gender” where it will declare as
a male or female as a value and male as a default value.
• The attribute type has a fixed value “sender”-->
<!DOCTYPE Letter SYSTEM "prac_9.dtd">
<Letter>
	<contact type="sender">
		<name>sujal</name>
		<address>nikol</address>
		<city>ahmedabad</city>
		<pin>859645</pin>
		<state>gujarat</state>
		<flag gender="male"></flag>
	</contact>
	<salutation>zdcd</salutation>
	<paragraph>scds</paragraph>
	<closing>cxdsc</closing>
	<signature>dsdd</signature>
</Letter>
