=== Sujal-prajapati07/College_programs/XML/exam_practice/ch2_4.dtd
<!ELEMENT students (Student_Name,Personal_Info,Result)>
<!ELEMENT Student_Name (#PCDATA)>
<!ELEMENT Personal_Info (Address,Birthdate,Gender,MobileNo)>
<!ELEMENT Address (#PCDATA)>
<!ELEMENT Birthdate (#PCDATA)>
<!ELEMENT Gender ( Male | Female )>
<!ELEMENT Male (#PCDATA)>
<!ELEMENT Female (#PCDATA)>
<!ELEMENT MobileNo (#PCDATA)>
<!ELEMENT Result (Total,Percentage,Grade)>
<!ELEMENT Total (#PCDATA)>
<!ELEMENT Percentage (#PCDATA)>
<!ELEMENT Grade ( Pass | Fail | Dist | Second)>
<!ELEMENT Pass (#PCDATA)>
<!ELEMENT Fail (#PCDATA)>
<!ELEMENT Dist (#PCDATA)>
<!ELEMENT Second (#PCDATA)>

=== Sujal-prajapati07/College_programs/XML/exam_practice/ch2_4.xml
<?xml version="1.0"?>
<!--Create XML document for Student where it contains the following 
data:
Student Name, Personal Info (Address, Birthdate,Gender, Mobile
No, Address) ,Result(Total, Percentage, Grade)
Create External DTD declaration for Student where 
â€¢ Gender has only two choices Male and Female as an element.
â€¢ Grade element should have only one of these grade element 
(Pass, First, Dist., Second, Fail)-->
<!DOCTYPE students SYSTEM "ch2_4.dtd">
<students>
	<Student_Name>Sujal</Student_Name>
	<Personal_Info>
		<Address>Ahmedabad</Address>
		<Birthdate>05/06/2024</Birthdate>
		<Gender>
			<Male>yes</Male>
		</Gender>
		<MobileNo>8574968515</MobileNo>
	</Personal_Info>
	<Result>
		<Total>650</Total>
		<Percentage>87</Percentage>
		<Grade>
			<Pass>yes</Pass>
		</Grade>
	</Result>
</students>
