=== Sujal-prajapati07/College_programs/XML/exam_practice/ch2_6.dtd
<!ELEMENT Student (Name,Id,Plan)>
<!ELEMENT Name (fname,lname)>
<!ELEMENT fname (#PCDATA)>
<!ELEMENT lname (#PCDATA)>
<!ELEMENT Id (#PCDATA)>
<!ELEMENT Plan (courses*)>
<!ATTLIST courses  year CDATA #REQUIRED>
<!ELEMENT courses (course)>
<!ELEMENT course (c_name,shortName,record)>
<!ELEMENT c_name (#PCDATA)>
<!ELEMENT shortName (#PCDATA)>
<!ELEMENT record (grade,date)>
<!ELEMENT grade (#PCDATA)>
<!ELEMENT date (#PCDATA)>

=== Sujal-prajapati07/College_programs/XML/exam_practice/ch2_6.xml
<?xml version="1.0"?>
<!--Create an XML document Student where it contains the following data:
Student(Name (fname & Lname) , ID , Plan (courses) ). In
courses element take (year) as an attribute and (course) as an
sub-element . And Course has name , shortName , record as its
sub element. And again record has its sub element Grade , date.
Create An External DTD for the above XML document where :
• Courses element can zero or more course.
• Year attribute must appear in the element.
• Record element should appear zero or more times-->
<!DOCTYPE Student SYSTEM "ch2_6.dtd">
<Student>
	<Name>
		<fname>Sujal</fname>
		<lname>Prajapati</lname>
	</Name>
	<Id>201</Id>
	<Plan>
		<courses year="2024">
			<course>
				<c_name>imscit</c_name>
				<shortName>it</shortName>
				<record>
					<grade>A</grade>
					<date>05/07/2023</date>
				</record>
			</course>
		</courses>
		<courses year="2024">
			<course>
				<c_name>imscit</c_name>
				<shortName>it</shortName>
				<record>
					<grade>A</grade>
					<date>05/07/2023</date>
				</record>
			</course>
		</courses>
	</Plan>
</Student>
